version: '3.8'

services:
  orders-service:
    build: ./OrdersService
    container_name: orders-service
    env_file: ./OrdersService/.env
    ports:
      - "3000:3000"   # Swagger: http://localhost:3000/api-docs
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - soanet

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    env_file: ./PaymentService/.env
    ports:
      - "3001:3001"   # Swagger: http://localhost:3001/api-docs
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - soanet

  shipping-service:
    build: ./ShippingService
    container_name: shipping-service
    env_file: ./ShippingService/.env
    ports:
      - "3002:3002"   # Swagger: http://localhost:3002/api-docs
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - soanet

  mongo:
    image: mongo:7.0
    container_name: soadb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - soanet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: soarbmq
    ports:
      - "5672:5672"       # AMQP for services
      - "15672:15672"     # RabbitMQ Management UI
    networks:
      - soanet

networks:
  soanet:
    driver: bridge

volumes:
  mongo-data:
