version: '3.8'

services:
  orders-service:
    build: ./OrdersService
    container_name: orders-service
    env_file: ./OrdersService/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - soanet

  mongo:
    image: mongo:7.0
    container_name: orders-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - soanet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders-rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    networks:
      - soanet

networks:
  soanet:
    driver: bridge

volumes:
  mongo-data:
