version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: orders-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ordersdb
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orders-service:
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo:27017/ordersdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo-data:
