version: "3.9"

services:
  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: cataloguser
      MYSQL_PASSWORD: catalogpass
    ports:
      - "3307:3306"
    volumes:
      - catalog_data:/var/lib/mysql

  catalog-service:
    build: .
    container_name: catalog-service
    restart: always
    depends_on:
      - catalog-db
    environment:
      DB_HOST: catalog-db
      DB_PORT: 3306
      DB_NAME: catalogdb
      DB_USER: cataloguser
      DB_PASS: catalogpass
    ports:
      - "8081:8080"   # Map Tomcat’s 8080 to host 8081

volumes:
  catalog_data:
