# Step 1: Use Maven to build the WAR
FROM maven:3.9.8-eclipse-temurin-17 AS builder

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Step 2: Use Tomcat to deploy the WAR
FROM tomcat:9.0-jdk17-temurin

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy built WAR into Tomcat webapps
COPY --from=builder /app/target/CatalogService.war /usr/local/tomcat/webapps/CatalogService.war

# Expose default Tomcat port
EXPOSE 8080

CMD ["catalina.sh", "run"]
